version: '3.8'

services:
  sportech:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8001:8001"
  postgres:
    image: postgres:14
    entrypoint: /entrypoint.sh
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/entrypoint.sh:/entrypoint.sh
      - ./postgres/create_databases.sh:/startup-initdb.d/create_databases.sh
      - ./postgres/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    tty: true
    stdin_open: true