DROP TABLE IF EXISTS team_managers;
DROP TABLE IF EXISTS team_players;
DROP TABLE IF EXISTS persons;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS leagues;
DROP TABLE IF EXISTS stadiums;
DROP TABLE IF EXISTS countries;
