name: Teams CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sportech-ci.yaml'
      - 'commons/**'
      - 'config/**'
      - 'database/**'
      - 'middleware/**'
      - 'team/**'
      - 'main.go'
  pull_request:
    paths:
      - '.github/workflows/sportech-ci.yaml'
      - 'commons/**'
      - 'config/**'
      - 'database/**'
      - 'middleware/**'
      - 'team/**'
      - 'main.go'

defaults:
  run:
    shell: bash
    working-directory: ./

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install golang-migrate
        shell: bash
        run: |
          if [[ $(migrate --version 2>&1) != ${{ inputs.golang_migrate_version }} ]]; then
            curl -L https://github.com/golang-migrate/migrate/releases/download/${{ inputs.golang_migrate_version }}/migrate.linux-amd64.tar.gz | tar xvz -C ${{ inputs.bin_dir }}
          fi

      - name: Build
        run: make build

      - name: Test
        run: make test
